intern4/urls.py
from django.contrib import admin
from django.urls import path , include
from intern4 import views

app_name = 'intern4'

urlpatterns =[
    path('',views.base,name='base'),
    path('newpage/',views.newpage,name='newpage'),
    path('getstarted/',views.getstarted,name='getstarted'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('intern4.urls'))
]

intern4/models.py
from django.db import models

# Create your models here.

intern4/views.py
from django.shortcuts import render

# Create your views here.
def base(request):
    return render(request,'internship4.html')

def getstarted(request):
    return render(request,'getstarted.html')

def newpage(request):
    return render(request,'newpage.html')

intern4/templates/getstarted.html
<html>
{% load static %}  
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Page Title</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static "css\internship4.css" %}">
    <script src="https://www.gstatic.com/firebasejs/5.7/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.7/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.7/firebase-auth.js"></script>
    <script type="text/javascript" src="{% static "js\jquery.js" %}"></script>
    <script src="{% static "js\initialize.js" %}"></script>
    <script src="{% static "js\listener.js" %}"></script>
    <script src="{% static "js\login.js" %}"></script>
    
  </head>

  <body style="background-color:rgb(195, 195, 195)">
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href="{% url 'intern4:base' %}" style="all: unset;color:grey;cursor: pointer;font-size: 17px;;"><strong>Home</strong></a>
    <h1 style="text-align: center;">Join Blogging</h1>
    <h3 style="text-align: center;">Create an account to personalize your <br> homepage, follow your favorite authors and <br>publications, applaud stories you love, and<br> more.</h3>
    <button class="loginBtn loginBtn--facebook" onclick="fbSignup()">
            Sign up with Facebook
          </button><br>



    <button class="loginBtn loginBtn--google" onclick="googleSignup()">
          Sign up with Google
         </button><br><br>

    <h5 style="display: table;margin: 0 auto;">
      </h5><h3 style="display: table;margin: 0 auto;">Already have an account?</h3><br>
      <!-- <a style="display: table;margin: 0 auto;background-color: rgb(250, 244, 244);">Sign in</a></h5> -->
      <button class="loginBtn loginBtn--facebook" onclick="fbSignup()">
          Sign in
      </button><br>

      <button class="loginBtn loginBtn--google" onclick="googleSignin()">
        Sign in
      </button>


    <br><br>
    <h3 style="text-align: center;">To make Blogging work, we log user data and share it with <br> service providers. Click “Sign up” above to accept Blogging’s <br> Terms of Service &amp; Privacy Policy.</h3>




</body></html>

intern4/templates/internship4.html
{% load static %}
<html lang="en"><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static "css\internship4.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" src="jquery.js"></script>
    <script type="text/javascript" src="main.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.7/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.7/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.7/firebase-auth.js"></script>
    <script type="text/javascript" src="{% static "js\jquery.js" %}"></script>
    <script src="{% static "js\initialize.js" %}"></script>
    <script src="{% static "js\listener.js" %}"></script>
    <script src="{% static "js\login.js" %}"></script>


    <title>Document</title>
  </head>

  <body style="background-color: rgb(163, 163, 163); margin: 0px 50px 0px 50px;padding-top: 5px;">

    <div class="logo">

      <span class="logo-name">Blogging</span>
      <button class="start-btn" id="get-started" onclick="divert()">Get started</button>


        <span class="fake-input">
                <input type="text" placeholder="        Google Search">
                <img src="{% static "img\search.jpg" %}" style="position: relative" width="30" height="30">
        </span><br>




        <span class="count">
          <div class="main_container" id="id_main_container">

                        <div class="container_inner">Total Views :
                          <span class="num_tiles" id="display_div_pageViews"><p id="display_div_pageViews">1847</p></span>
                          <!-- <span class="num_tiles">0</span>
                          <span class="num_tiles">1</span>
                          <span class="num_tiles">0</span>
                          <span class="num_tiles">0</span>
                          <span class="num_tiles">0</span>  -->
                        </div>
                      </div>
          <div class="main_container" id="id_main_container">

                        <div class="container_inner">Total Users :
                          <span class="num_tiles" id="display_div_usersCount">27479</span>
                          <!-- <span class="num_tiles">0</span>
                          <span class="num_tiles">1</span>
                          <span class="num_tiles">0</span>
                          <span class="num_tiles">0</span>
                          <span class="num_tiles">0&nbsp</span>  -->
                        </div>
                       </div>
          </span>
    </div><br><br><br>



    <header class="nav">
      <div class="nav-box">
        <span class=""><a href="#">Home</a></span>&nbsp;&nbsp;
        <span class=""><a href="#">Nation</a></span>&nbsp;&nbsp;
        <span class=""><a href="#">Sports</a></span>&nbsp;&nbsp;
        <span class=""><a href="#">Politics</a></span>&nbsp;&nbsp;
        <span class=""><a href="#">Entertainment</a></span>&nbsp;&nbsp;
        <span class=""><a href="#">Search</a></span>&nbsp;&nbsp;
        <span class=""><a href="#">Contact Us</a></span>
      </div>
    </header>
    <hr>



    <table class="section1">
      <tbody><tr>
        <td style="text-align: left; padding: 5px; padding-top: 20px;">
          <span class="featured1" style="text-align: left; padding: 0px;">
                                <img src="{% static "img\twitter.png" %}" alt="" width="400" height="150">
                                <p></p><h2>Should Twitter Get Rid of Follower Counts?</h2>
                                        <h3>The possibility feels closer than ever</h3>
                                        Cool Neha in All Things Creative<br>
                                        <h4>Jan 9  ·  5 min read</h4>

                                    <p></p>
                            </span>

        </td>
        <td style="padding-top: 14px;">
          <span class="top3">

                                <span><img src="{% static "img\html.jpg" %}" alt="" style="float: left;border: 1px solid black;margin: 22px 10px 10px 0px;" width="100" height="100">
                                   <h3>Html, a standardized system for tagging text files to achieve font, colour, graphic, and hyperlink effects on WWW pages.</h3>

                                </span><br>


          <span style="float: left;"><p style=""></p><img src="{% static "img\css.png" %}" alt="" style="float: left;border: 1px solid black;margin: 0px 10px 10px 0px;" width="100" height="100">
                                <h3>CSS describes how HTML elements are to be displayed on screen, paper, or in other media &amp; control the layout of multiple web pages.</h3>
                                </span><br>


          <span style="float: left;"><p style=""></p><img src="{% static "img\nfl.png" %}" alt="" style="float: left;border: 1px solid black;margin: 5px 10px 10px 0px;" width="100" height="100">
                                <h3>Teach yourself the foundations of designing using these links made for learning.--freecodecamp &amp; theodinproject</h3>
                                </span>

          </span>

        </td>
        <td style="text-align: left; padding: 5px;">
          <span class="featured2">
                                <span class="newpage" onclick="article()"><img src="{% static "img\featured3.jpg" %}" alt=" " width="400" height="150">
                                    <p></p><h2>No, That’s Not How You Say It</h2>
                                        <h3>A short personal history of my favorite fast food<br>(<a href="{% url 'intern4:newpage' %}">Read more...</a>)</h3>
                                        VIP Singh <br>
                                        <h4>Jan 29 · 8 min read</h4><p></p>
                                </span>
                          </span>

                </td>
            </tr>
        </tbody></table><hr>




        <div class="section2 ">
            <span class="site-media ">
                <img src="{% static "img\circuit.png" %}" alt=" ">
            </span>
        </div><hr>



        <table class="section3 ">
                <tbody><tr>
                    <td style="text-align: left; padding: 5px; padding-top: 20px; ">
                            <span class="featured1 " style="text-align: left; padding: 0px; ">
                                    <img src="{% static "img\code.jpg" %}" alt=" " width="400" height="150">
                                    <p></p><h2>A few good reasons why you should learn to code</h2>
                                            <h3>You might be wondering if learning to code is something you should...</h3>
                                            Admin <br>
                                            <h4>Jan 9  ·  5 min read</h4>

                                        <p></p>
                                </span>

                    </td>
                    <td style="padding-top: 14px; ">
                            <span class="top3 ">

                                    <span><img src="{% static "img\invest.png" %}" alt=" " style="float: left;border: 1px solid black;margin: 22px 10px 10px 0px; " width="100 " height="100 ">
                                       <h3>Only buy something that you’d be perfectly happy to hold if the market shut down for 10 years.</h3>

                                    </span><br>


                                    <span style="float: left; "><p style=" "></p><img src="{% static "img\grills.jpg" %}" alt=" " style="float: left;border: 1px solid black;margin: 0px 10px 10px 0px; " width="100 " height="100 ">
                                    <h3>When I figured out how to work my grill, it was quite a moment. I discovered that summer is a completely different experience when you know how to grill.</h3>
                                    </span><br>


                                    <span style="float: left; "><p style=" "></p><img src="{% static "img\chain.png" %}" alt=" " style="float: left;border: 1px solid black;margin: 5px 10px 10px 0px; " width="100 " height="100 ">
                                    <h3> Chains of habit are too light to be felt until they are too heavy to be broken.</h3>
                                    </span>

                              </span>

                    </td>
                    <td style="text-align: left; padding: 5px; ">
                            <span class="featured2 " "="">
          <span><img src="{% static "img\beach.jpg" %}" alt="" width="400" height="150">
                                        <p></p><h2>Deep space radio waves baffle astronomers; aliens not ruled out</h2>
                                            <h3> Every time we see something we’ve never seen before that is an opportu..</h3>
                                            Enzyme Snehar<br>
                                            <h4>Jan 29 · 8 min read</h4><p></p>
                                    </span>
          </span>

        </td>
      </tr>
    </tbody></table>
    <hr>




    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <br>
          <div class="aboutus">
            <a href="#">About us</a><a>Privacy policy</a><a>Newsletter</a><a>Sitemap</a>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text"><b>FOLLOW US ON</b></h5>
            <a class="fa fa-facebook" href="https://www.facebook.com/suvenconsultants/"></a>
            <a class="fa fa-twitter"></a>
            <a class="fa fa-google" href="https://www.google.co.in/search?nfpr=1&amp;q=suven+consultants&amp;spell=1&amp;sa=X&amp;ved=0ahUKEwidoubh1dXdAhWFNY8KHfrxBZoQBQgpKAA&amp;biw=1366&amp;bih=657#lrd=0x3be7c8afbfffffff:0xcf0cd79d3c52220a,1,,,"></a>
            <a class="fa fa-rss"></a>
            <a class="fa fa-youtube" href="https://www.youtube.com/user/rockyjagtiani"></a>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          <h5>
            <p>Copyright © 2019 <a>Private Institution</a>All rights reserved
            </p>
          </h5><br>
        </div>
      </div>
    </footer>
    <script>
        function divert() {
          window.location.href = "{% url 'intern4:getstarted' %}"
        }
        function article(){
          window.location.href = "{% url 'intern4:newpage' %}"
        }
      </script>
<script>


    $(document).ready(function(){

  $.ajax({
    type: 'post',
    data: {
      updateTotalViews: "pageViews"
    },

    success: function(response) {
      $('#display_div_pageViews').html(response);

    }
  });




  $.ajax({
    type: 'post',
    data: {
      readTotalUsers: "usersCount"
    },

    success: function(response) {
      $('#display_div_usersCount').html(response);

    }
  });
});

    </script>
    <script type="text/javascript">
      $(document).ready(function () {
          $("body").on("contextmenu",function(e){
              return false;
          });
      });
    </script>



</body></html>

intern4/templates/newpage.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" type="text/css" href="{% static "css\internship4.css" %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <script type="text/javascript" src="jquery.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.7/firebase.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.7/firebase-app.js"></script>
    <script src="https://www.gstatic.com/firebasejs/5.7/firebase-auth.js"></script>
    <script type="text/javascript" src="{% static "js\jquery.js" %}"></script>
    <script src="{% static "js\initialize.js" %}"></script>
    <script src="{% static "js\listener.js" %}"></script>
    <script src="{% static "js\login.js" %}"></script>
    <title></title>
</head>
<body style="background-color: rgb(197, 194, 194); margin: 0px 50px 0px 50px;padding-top: 5px;">


  <header class="nav">
    <div class="nav-box">
      <span class=""><a href="{% url 'intern4:base' %}">Home</a></span>&nbsp&nbsp
      <span class=""><a href="#">Nation</a></span>&nbsp&nbsp
      <span class=""><a href="#">Sports</a></span>&nbsp&nbsp
      <span class=""><a href="#">Politics</a></span>&nbsp&nbsp
      <span class=""><a href="#">Entertainment</a></span>&nbsp&nbsp
      <span class=""><a href="#">Search</a></span>&nbsp&nbsp
      <span class=""><a href="#">Contact Us</a></span>
    </div>
  </header>
  <hr>
        <!-- &nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp&nbsp<a href="index.html" style="all: unset;color:grey;cursor: pointer;font-size: 17px;;"><strong>Home</strong></a> -->

    <span class="details">

            <img src="{% static "img\featured3.jpg" %}" alt="">
        <br><br><br><br><br><br><p><strong><EM>MEMBER FEATURE STORY</EM></strong></p><br>

                <p>No, That’s Not How You Say It</p>
                <p>A short personal history of my favorite fast food
                </p>
                <div style="display:inline">
                    <input class="nodetails" type="image" src="{% static "img\like.png" %}" id="like_button" name="" value="">
                    <input class="nodetails" type="image" src="{% static "img\dislike.jpg" %}" id="dislike_button" name="" value="">
                    <div id="totalvotes"></div>
                </div>

                <br>

                <br>

       <p><span class="graf-dropCap">I</span>ndians talk funny. We don’t think we do, but we do. We’re usually too busy talking at or over or directly through each other to notice. Every so often, though, we stop long enough to listen to one another and then laugh and point.</p>
            <p name="f84e" id="f84e" class="graf graf--p graf-after--p">The middle-aged Persian woman I hired to teach me how to drive made fun of me when I mispronounced Cahuenga Boulevard. I had just moved to Mumbai a few months prior from Yamunotri, where I considered myself a native despite the disagreements of many native Mumbaikars. Frank Lloyd Wright once said, “tip the world over on its side and everything loose will land in Mumbai.” So I floated across the country&#8202;—&#8202;as millions before me had&#8202;—&#8202;to seek my fortune.</p>
            <p name="fb82" id="fb82" class="graf graf--p graf-after--p">Her teaching method was an unorthodox form of politically incorrect mockery. When I tapped the brakes too hard, she’d tell me not to drive like a “Chinaman” and then pantomimed her head flinging back and forth, as if she were bowing. She casually informed me that Mumbaikars were notoriously terrible at changing lanes. Don’t get her started on Indians. Seriously, don’t. She was, to be charitable, racially insensitive.</p>
            <p name="5ccb" id="5ccb" class="graf graf--p graf-after--p">I was a stranger in her city but my advanced age and inexperience amused her. How could a grown man not know how to drive a car? It was, however, my accent that intrigued her the most. I spoke with the faintest southern drawl but I also had northeastern motormouth tendencies. She was always drawing conclusions as to my ethnicity.</p>
            <p name="8e24" id="8e24" class="graf graf--p graf-after--p">During one lesson she said, “You people are good drivers.”</p>
            <p name="92bc" id="92bc" class="graf graf--p graf-after--p">You people?</p>
            <p name="00c4" id="00c4" class="graf graf--p graf--startsWithDoubleQuote graf-after--p">“<em class="markup--em markup--p-em">Mumbaikars</em>.”</p>
            <p name="1452" id="1452" class="graf graf--p graf-after--p">Because of her I passed my driver’s test, got my first license to operate a motor vehicle, and then proceeded to not drive for years. Everything I needed was in walking distance: my job and places to eat.</p>
            <p name="6e4a" id="6e4a" class="graf graf--p graf-after--p">Here’s the truth about food in India: it’s pretty good. There’s amazing pho and pupusas and bulgogi. During my three year internment in the city of Mumbai, I was able to find satisfactory replacements for my beloved street foods. I found some decent pizza. I even found bagels that… sufficed. But I could never find the one dish that reminded me of my adopted home for the previous 16 years. A gyro platter.</p>
            <p name="41bd" id="41bd" class="graf graf--p graf-after--p">I couldn’t even find a suitable Mumbai-style Greek diner, the kind of greasy spoon with a massive menu where you can order a meal of waffles, meatloaf, and lasagna if you want.</p>
            <p name="0cf4" id="0cf4" class="graf graf--p graf-after--p">But it’s not as if Mumbai has no roast meat sandwiches. My racist&#8202;—&#8202;but friendly&#8202;—&#8202;driving instructor had once pointed out an Armenian restaurant that she recommended. This place served up delicious chicken shawarma sandwiches and a garlic sauce I could eat with my fingers.</p>
            <p name="59f5" id="59f5" class="graf graf--p graf-after--p graf--trailing">Eventually, I would drift back to Mumbai. The first thing I would order upon my return? A gyro, a word that rhymes with “pie-whoa.”</p>
    </span>
    <hr>
    <footer class="page-footer">
      <div class="container">
        <div class="row">
          <br>
          <div class="aboutus">
            <a href="#">About us</a><a>Privacy policy</a><a>Newsletter</a><a>Sitemap</a>
          </div>
          <div class="col l4 offset-l2 s12">
            <h5 class="white-text"><b>FOLLOW US ON</b></h5>
            <a class="fa fa-facebook"  href="https://www.facebook.com/suvenconsultants/"></a>
            <a class="fa fa-twitter"></a>
            <a class="fa fa-google"  href="https://www.google.co.in/search?nfpr=1&q=suven+consultants&spell=1&sa=X&ved=0ahUKEwidoubh1dXdAhWFNY8KHfrxBZoQBQgpKAA&biw=1366&bih=657#lrd=0x3be7c8afbfffffff:0xcf0cd79d3c52220a,1,,,"></a>
            <a class="fa fa-rss"></a>
            <a class="fa fa-youtube" href="https://www.youtube.com/user/rockyjagtiani" ></a>
          </div>
        </div>
      </div>
      <div class="footer-copyright">
        <div class="container">
          <h5>
            <p>Copyright © 2019 <a>Suven Consultants and technology pvt ltd</a>All rights reserved</b>
            </p>
          </h5><br>
        </div>
      </div>
    </footer>

    <script>
        $(document).ready(function(){


$('#like_button').click(function insert_like() {
  $.ajax({
    type: 'post',
    data: {
      post_like: "like"
    },

    success: function(response) {
      $('#totalvotes').slideDown(50);
      $('#totalvotes').html(response);

    }
  });
});


$('#dislike_button').click(function insert_dislike() {
  $.ajax({
    type: 'post',
    data: {
      post_dislike: "dislike"
    },

    success: function(response) {
      $('#totalvotes').slideDown(50);
      $('#totalvotes').html(response);

    }
  });
});

});

    </script>
</body>
</html>